import { Shield, FileText, Mail } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="no-print border-t border-slate-800/80 bg-slate-900/60">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Legal sections grid */}
        <div className="grid md:grid-cols-2 gap-8 mb-10">
          {/* Privacy Policy */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-md bg-emerald-500/15 border border-emerald-500/20 flex items-center justify-center">
                <Shield size={14} className="text-emerald-400" />
              </div>
              <h4 className="text-sm font-semibold text-slate-200">Privacy Policy</h4>
            </div>
            <p className="text-xs text-slate-500 leading-relaxed">
              We respect your privacy. All user form inputs, data selections, and typed digital signature generations are fully executed locally inside your personal web browser. We do not host, store, track, collect, or transmit any private user data to external cloud server systems.
            </p>
          </div>

          {/* Terms of Service */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-md bg-amber-500/15 border border-amber-500/20 flex items-center justify-center">
                <FileText size={14} className="text-amber-400" />
              </div>
              <h4 className="text-sm font-semibold text-slate-200">Terms of Service &amp; Disclaimer</h4>
            </div>
            <p className="text-xs text-slate-500 leading-relaxed">
              Disclaimer: Document templates and agreement drafts generated by this website are for interpersonal accountability and informational purposes only. This tool does not represent professional attorney legal counsel. We claim absolute zero liability for any rental disputes, financial losses, or housing issues.
            </p>
          </div>
        </div>

        {/* Bottom bar */}
        <div className="pt-6 border-t border-slate-800/60 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-slate-500">
              &copy; 2026 FreeChoreContract.com. All rights reserved.
            </span>
          </div>
          <a
            href="mailto:support@freechorecontract.com"
            className="flex items-center gap-2 text-xs text-slate-400 hover:text-sky-400 transition-colors group"
          >
            <Mail size={13} className="group-hover:text-sky-400 transition-colors" />
            support@freechorecontract.com
          </a>
        </div>
      </div>
    </footer>
  );
}
